// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	Code    OptInt32  `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val OptString) {
	s.Message = val
}

func (*BadRequestError) createOrderRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	Code    OptInt32  `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val OptString) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	UserUUID  uuid.UUID   `json:"user_uuid"`
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	OrderUUID  OptUUID    `json:"order_uuid"`
	TotalPrice OptFloat64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() OptUUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() OptFloat64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val OptUUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val OptFloat64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	OrderUUID       OptUUID          `json:"order_uuid"`
	UserUUID        OptUUID          `json:"user_uuid"`
	PartUuids       []uuid.UUID      `json:"part_uuids"`
	TotalPrice      OptFloat64       `json:"total_price"`
	TransactionUUID OptUUID          `json:"transaction_uuid"`
	PaymentMethod   OptPaymentMethod `json:"payment_method"`
	Status          OptOrderStatus   `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() OptUUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() OptUUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() OptFloat64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() OptOrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val OptUUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val OptUUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val OptFloat64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val OptOrderStatus) {
	s.Status = val
}

func (*GetOrderResponse) getOrderRes() {}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	Code    OptInt32  `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val OptString) {
	s.Message = val
}

func (*InternalServerError) createOrderRes() {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	Code    OptInt32  `json:"code"`
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val OptString) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes() {}
func (*NotFoundError) getOrderRes()    {}
func (*NotFoundError) payOrderRes()    {}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderStatus returns new OptOrderStatus with value set to v.
func NewOptOrderStatus(v OrderStatus) OptOrderStatus {
	return OptOrderStatus{
		Value: v,
		Set:   true,
	}
}

// OptOrderStatus is optional OrderStatus.
type OptOrderStatus struct {
	Value OrderStatus
	Set   bool
}

// IsSet returns true if OptOrderStatus was set.
func (o OptOrderStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderStatus) Reset() {
	var v OrderStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderStatus) SetTo(v OrderStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderStatus) Get() (v OrderStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderStatus) Or(d OrderStatus) OrderStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusORDERSTATUSUNSPECIFIED    OrderStatus = "ORDER_STATUS_UNSPECIFIED"
	OrderStatusORDERSTATUSPENDINGPAYMENT OrderStatus = "ORDER_STATUS_PENDING_PAYMENT"
	OrderStatusORDERSTATUSPAID           OrderStatus = "ORDER_STATUS_PAID"
	OrderStatusORDERSTATUSCANCELLED      OrderStatus = "ORDER_STATUS_CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusORDERSTATUSUNSPECIFIED,
		OrderStatusORDERSTATUSPENDINGPAYMENT,
		OrderStatusORDERSTATUSPAID,
		OrderStatusORDERSTATUSCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusORDERSTATUSUNSPECIFIED:
		return []byte(s), nil
	case OrderStatusORDERSTATUSPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusORDERSTATUSPAID:
		return []byte(s), nil
	case OrderStatusORDERSTATUSCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusORDERSTATUSUNSPECIFIED:
		*s = OrderStatusORDERSTATUSUNSPECIFIED
		return nil
	case OrderStatusORDERSTATUSPENDINGPAYMENT:
		*s = OrderStatusORDERSTATUSPENDINGPAYMENT
		return nil
	case OrderStatusORDERSTATUSPAID:
		*s = OrderStatusORDERSTATUSPAID
		return nil
	case OrderStatusORDERSTATUSCANCELLED:
		*s = OrderStatusORDERSTATUSCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	TransactionUUID OptUUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODUNSPECIFIED   PaymentMethod = "PAYMENT_METHOD_UNSPECIFIED"
	PaymentMethodPAYMENTMETHODCARD          PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP           PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD    PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMONEY PaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODUNSPECIFIED,
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		*s = PaymentMethodPAYMENTMETHODUNSPECIFIED
		return nil
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
